// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnMf1yvv85GhoIYp5S8ipaajyK62p9ejo',
    appId: '1:987608429996:web:0b5aea728b2b86a14db609',
    messagingSenderId: '987608429996',
    projectId: 'example-edca8',
    authDomain: 'example-edca8.firebaseapp.com',
    databaseURL: 'https://example-edca8-default-rtdb.firebaseio.com',
    storageBucket: 'example-edca8.firebasestorage.app',
    measurementId: 'G-7YNFV3Y26Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHJicSMCXNi7EVpBChkA1rld8QdIViupo',
    appId: '1:987608429996:android:f0a1fa3951c4e1864db609',
    messagingSenderId: '987608429996',
    projectId: 'example-edca8',
    databaseURL: 'https://example-edca8-default-rtdb.firebaseio.com',
    storageBucket: 'example-edca8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Rp2Mu-Os22ss10e0owsxERZIrFlacJY',
    appId: '1:987608429996:ios:3c8a89d5df8902aa4db609',
    messagingSenderId: '987608429996',
    projectId: 'example-edca8',
    databaseURL: 'https://example-edca8-default-rtdb.firebaseio.com',
    storageBucket: 'example-edca8.firebasestorage.app',
    iosBundleId: 'com.rollcake.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Rp2Mu-Os22ss10e0owsxERZIrFlacJY',
    appId: '1:987608429996:ios:3c8a89d5df8902aa4db609',
    messagingSenderId: '987608429996',
    projectId: 'example-edca8',
    databaseURL: 'https://example-edca8-default-rtdb.firebaseio.com',
    storageBucket: 'example-edca8.firebasestorage.app',
    iosBundleId: 'com.rollcake.firebaseExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnMf1yvv85GhoIYp5S8ipaajyK62p9ejo',
    appId: '1:987608429996:web:8fa1cb2393adff684db609',
    messagingSenderId: '987608429996',
    projectId: 'example-edca8',
    authDomain: 'example-edca8.firebaseapp.com',
    databaseURL: 'https://example-edca8-default-rtdb.firebaseio.com',
    storageBucket: 'example-edca8.firebasestorage.app',
    measurementId: 'G-KB498TWWMN',
  );
}
